update and lock deps
matehat/cqex pull request #23
Opened 2017-03-05 12:11 UTC by piglovesyou

fix #22 

After I update deps, the error `fatal error: re2/re2.h: No such file or directory` has gone.

Or if we're still in developing phase, we could remove the mix.lock file from the project.

2017-07-03 17:10 UTC, matehat requested changes
Thanks for contributing!

Can you explain why you wanted to hardcode picking the mix.lock file from your top-level project?

2017-07-03 17:10 UTC, matehat commented on mix.exs
> +     lockfile: "../../mix.lock",
Not sure that this should be here ..

2017-07-03 23:53 UTC, piglovesyou commented
@matehat Thank you for your reviewing. Right, it seems a mistake, I'll check it in a couple of days.

2017-09-21 12:18 UTC, matehat approved these changes

2017-09-21 12:19 UTC, merged

2017-09-22 06:08 UTC, piglovesyou commented
Sorry I couldn't do that. Thanks for your help. @matehat

2017-09-22 10:23 UTC, matehat commented
No problem 🙂